CREATE TABLE COMMENTS (
   COMMENTID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
   MOVIEID INT,
   COMMENT VARCHAR (1000),
   IPADDRESS VARCHAR (225),
   STAMPDATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4;